class AppStrings {
  const AppStrings(this.languageCode);

  final String languageCode;

  String t(String key) {
    final localized = _values[languageCode]?[key];
    return localized ?? _en[key] ?? key;
  }

  static const Map<String, String> _en = {
    'appName': 'TripBanBan',
    'trips': 'Trips',
    'records': 'Records',
    'add': 'Add',
    'settlement': 'Settlement',
    'settings': 'Settings',
    'myTrips': 'My Trips',
    'newTrip': 'Create new trip',
    'noTrips': 'No trips yet. Create your first trip.',
    'notStarted': 'Not started',
    'pending': 'To settle',
    'settled': 'Settled',
    'publicFund': 'Shared fund',
    'balance': 'Balance',
    'members': 'Members',
    'manageMembers': 'Manage members',
    'deleteTrip': 'Delete trip',
    'expenseRecords': 'Expense records',
    'noExpenses': 'No expenses yet',
    'addExpense': 'Add expense',
    'tripProject': 'Trip project',
    'selectTrip': 'Select trip',
    'amount': 'Amount',
    'currency': 'Currency',
    'payer': 'Who paid?',
    'fund': 'Shared fund',
    'shareWith': 'Who shares it?',
    'selectAll': 'Select all',
    'clearAll': 'Clear all',
    'equal': 'Equal',
    'custom': 'Custom amount',
    'percentage': 'Percentage',
    'remaining': 'Remaining',
    'over': 'Over',
    'category': 'Category',
    'title': 'Expense detail',
    'note': 'Note',
    'save': 'Save',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'language': 'Language',
    'defaultCurrency': 'Default currency',
    'backup': 'Backup',
    'driveBackup': 'Google Drive backup',
    'connectGoogle': 'Connect Google Drive',
    'backupNow': 'Back up now',
    'restoreDrive': 'Restore from Google Drive',
    'localBackup': 'Export .tripbanban backup',
    'localRestore': 'Import .tripbanban backup',
    'fxUpdate': 'Update FX rates',
    'shareSettlement': 'Share settlement image',
    'shareCsv': 'Export CSV',
    'whoPaysWhom': 'Suggested transfers',
    'memberStats': 'Per-person spending',
    'paid': 'Paid',
    'shouldShare': 'Share',
    'net': 'Net',
    'markPaid': 'Mark paid',
    'fundNeedsRefund': 'The shared fund still has a balance. Refund it before final settlement.',
    'fundRefund': 'Shared fund refund',
    'totalExpense': 'Total expense',
    'done': 'Done',
    'error': 'Error',
  };

  // Locale maps contain overrides only. Any missing string falls back to English
  // through t(), which avoids duplicate const-map keys while keeping all ten
  // languages usable as translation coverage grows.
  static const Map<String, Map<String, String>> _values = {
    'en': _en,
    'zh_Hant': {
      'appName': '旅行伴伴',
      'trips': '旅程',
      'records': '紀錄',
      'add': '新增',
      'settlement': '結算',
      'settings': '設定',
      'myTrips': '我的旅程',
      'newTrip': '建立新旅程',
      'noTrips': '還沒有旅程，先建立第一趟旅行。',
      'notStarted': '未開始',
      'pending': '待結算',
      'settled': '已結清',
      'publicFund': '公基金',
      'balance': '餘額',
      'members': '旅伴',
      'manageMembers': '管理旅伴',
      'deleteTrip': '刪除旅程',
      'expenseRecords': '支出紀錄',
      'noExpenses': '目前沒有支出紀錄',
      'addExpense': '新增支出',
      'tripProject': '旅程專案',
      'selectTrip': '選擇旅程',
      'amount': '金額',
      'currency': '幣別',
      'payer': '誰付款？',
      'fund': '公基金',
      'shareWith': '誰需要分攤？',
      'selectAll': '全選',
      'clearAll': '取消全選',
      'equal': '平均',
      'custom': '自訂金額',
      'percentage': '比例',
      'remaining': '尚未分配',
      'over': '超出',
      'category': '分類',
      'title': '支出明細',
      'note': '備註',
      'save': '儲存',
      'delete': '刪除',
      'cancel': '取消',
      'language': '語言',
      'defaultCurrency': '預設幣別',
      'backup': '資料備份',
      'driveBackup': 'Google Drive 備份',
      'connectGoogle': '連結 Google Drive',
      'backupNow': '立即備份',
      'restoreDrive': '從 Google Drive 還原',
      'localBackup': '匯出 .tripbanban 備份',
      'localRestore': '匯入 .tripbanban 備份',
      'fxUpdate': '更新匯率',
      'shareSettlement': '分享結算長圖',
      'shareCsv': '匯出 CSV',
      'whoPaysWhom': '最後轉帳建議',
      'memberStats': '每人支出統計',
      'paid': '支出',
      'shouldShare': '分攤',
      'net': '淨額',
      'markPaid': '標記已付款',
      'fundNeedsRefund': '公基金仍有餘額，退款後才能完全結清。',
      'fundRefund': '公基金退款',
      'totalExpense': '總支出',
      'done': '完成',
      'error': '錯誤',
    },
    'zh_Hans': {
      'appName': '旅行伴伴',
      'trips': '旅程',
      'records': '记录',
      'add': '新增',
      'settlement': '结算',
      'settings': '设置',
      'myTrips': '我的旅程',
      'newTrip': '建立新旅程',
      'noTrips': '还没有旅程，先建立第一趟旅行。',
      'notStarted': '未开始',
      'pending': '待结算',
      'settled': '已结清',
      'publicFund': '公基金',
      'balance': '余额',
      'members': '旅伴',
      'manageMembers': '管理旅伴',
      'deleteTrip': '删除旅程',
      'expenseRecords': '支出记录',
      'noExpenses': '目前没有支出记录',
      'addExpense': '新增支出',
      'tripProject': '旅程项目',
      'selectTrip': '选择旅程',
      'amount': '金额',
      'currency': '币别',
      'payer': '谁付款？',
      'fund': '公基金',
      'shareWith': '谁需要分摊？',
      'equal': '平均',
      'custom': '自定义金额',
      'percentage': '比例',
      'category': '分类',
      'save': '保存',
      'cancel': '取消',
      'language': '语言',
      'defaultCurrency': '预设币别',
      'driveBackup': 'Google Drive 备份',
      'backupNow': '立即备份',
      'restoreDrive': '从 Google Drive 还原',
      'whoPaysWhom': '最终转账建议',
      'memberStats': '每人支出统计',
      'paid': '支出',
      'shouldShare': '分摊',
      'net': '净额',
      'fundRefund': '公基金退款',
      'totalExpense': '总支出',
    },
    'ja': {
      'trips': '旅行',
      'records': '支出記録',
      'add': '追加',
      'settlement': '精算',
      'settings': '設定',
      'newTrip': '新しい旅行を作成',
      'noTrips': '旅行がありません。最初の旅行を作成してください。',
      'notStarted': '未開始',
      'pending': '精算待ち',
      'settled': '精算済み',
      'publicFund': '共同資金',
      'members': 'メンバー',
      'addExpense': '支出を追加',
      'tripProject': '旅行プロジェクト',
      'selectTrip': '旅行を選択',
      'amount': '金額',
      'currency': '通貨',
      'payer': '誰が支払いましたか？',
      'shareWith': '誰が負担しますか？',
      'equal': '均等',
      'custom': '金額指定',
      'percentage': '割合',
      'category': 'カテゴリ',
      'save': '保存',
      'cancel': 'キャンセル',
      'language': '言語',
      'defaultCurrency': '既定通貨',
      'whoPaysWhom': '最終送金提案',
      'memberStats': '一人あたりの支出',
      'paid': '支出',
      'shouldShare': '負担',
      'net': '差額',
      'fundRefund': '共同資金の返金',
      'totalExpense': '総支出',
    },
    'ko': {
      'trips': '여행',
      'records': '지출 기록',
      'add': '추가',
      'settlement': '정산',
      'settings': '설정',
      'newTrip': '새 여행 만들기',
      'noTrips': '여행이 없습니다. 첫 여행을 만들어 보세요.',
      'notStarted': '시작 전',
      'pending': '정산 대기',
      'settled': '정산 완료',
      'publicFund': '공동 경비',
      'members': '멤버',
      'addExpense': '지출 추가',
      'tripProject': '여행 프로젝트',
      'selectTrip': '여행 선택',
      'amount': '금액',
      'currency': '통화',
      'payer': '누가 결제했나요?',
      'shareWith': '누가 분담하나요?',
      'equal': '균등',
      'custom': '직접 입력',
      'percentage': '비율',
      'category': '분류',
      'save': '저장',
      'cancel': '취소',
      'language': '언어',
      'defaultCurrency': '기본 통화',
      'whoPaysWhom': '최종 송금 제안',
      'memberStats': '개인별 지출 통계',
      'paid': '지출',
      'shouldShare': '분담',
      'net': '차액',
      'fundRefund': '공동 경비 환불',
      'totalExpense': '총지출',
    },
    'fr': {
      'trips': 'Voyages',
      'records': 'Dépenses',
      'add': 'Ajouter',
      'settlement': 'Règlement',
      'settings': 'Réglages',
      'newTrip': 'Créer un voyage',
      'noTrips': 'Aucun voyage. Créez votre premier voyage.',
      'notStarted': 'Non commencé',
      'pending': 'À régler',
      'settled': 'Réglé',
      'publicFund': 'Cagnotte',
      'members': 'Voyageurs',
      'addExpense': 'Ajouter une dépense',
      'tripProject': 'Projet de voyage',
      'selectTrip': 'Choisir un voyage',
      'amount': 'Montant',
      'currency': 'Devise',
      'payer': 'Qui a payé ?',
      'shareWith': 'Qui partage ?',
      'equal': 'Égal',
      'custom': 'Montant personnalisé',
      'percentage': 'Pourcentage',
      'category': 'Catégorie',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'language': 'Langue',
      'defaultCurrency': 'Devise par défaut',
      'whoPaysWhom': 'Transferts conseillés',
      'memberStats': 'Dépenses par personne',
      'paid': 'Dépensé',
      'shouldShare': 'Part',
      'net': 'Solde',
      'fundRefund': 'Rembourser la cagnotte',
      'totalExpense': 'Dépenses totales',
    },
    'de': {
      'trips': 'Reisen',
      'records': 'Ausgaben',
      'add': 'Hinzufügen',
      'settlement': 'Abrechnung',
      'settings': 'Einstellungen',
      'newTrip': 'Neue Reise',
      'noTrips': 'Noch keine Reise. Erstelle deine erste Reise.',
      'notStarted': 'Nicht begonnen',
      'pending': 'Offen',
      'settled': 'Abgerechnet',
      'publicFund': 'Gemeinschaftskasse',
      'members': 'Mitreisende',
      'addExpense': 'Ausgabe hinzufügen',
      'tripProject': 'Reiseprojekt',
      'selectTrip': 'Reise auswählen',
      'amount': 'Betrag',
      'currency': 'Währung',
      'payer': 'Wer hat bezahlt?',
      'shareWith': 'Wer teilt?',
      'equal': 'Gleich',
      'custom': 'Eigener Betrag',
      'percentage': 'Prozent',
      'category': 'Kategorie',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'language': 'Sprache',
      'defaultCurrency': 'Standardwährung',
      'whoPaysWhom': 'Empfohlene Überweisungen',
      'memberStats': 'Ausgaben pro Person',
      'paid': 'Ausgaben',
      'shouldShare': 'Anteil',
      'net': 'Saldo',
      'fundRefund': 'Kasse zurückzahlen',
      'totalExpense': 'Gesamtausgaben',
    },
    'es': {
      'trips': 'Viajes',
      'records': 'Gastos',
      'add': 'Añadir',
      'settlement': 'Liquidación',
      'settings': 'Ajustes',
      'newTrip': 'Crear viaje',
      'noTrips': 'Aún no hay viajes. Crea tu primer viaje.',
      'notStarted': 'No iniciado',
      'pending': 'Por liquidar',
      'settled': 'Liquidado',
      'publicFund': 'Fondo común',
      'members': 'Viajeros',
      'addExpense': 'Añadir gasto',
      'tripProject': 'Proyecto de viaje',
      'selectTrip': 'Elegir viaje',
      'amount': 'Importe',
      'currency': 'Moneda',
      'payer': '¿Quién pagó?',
      'shareWith': '¿Quién comparte?',
      'equal': 'Igual',
      'custom': 'Importe personalizado',
      'percentage': 'Porcentaje',
      'category': 'Categoría',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'language': 'Idioma',
      'defaultCurrency': 'Moneda predeterminada',
      'whoPaysWhom': 'Transferencias sugeridas',
      'memberStats': 'Gasto por persona',
      'paid': 'Gastado',
      'shouldShare': 'Parte',
      'net': 'Saldo',
      'fundRefund': 'Reembolso del fondo',
      'totalExpense': 'Gasto total',
    },
    'it': {
      'trips': 'Viaggi',
      'records': 'Spese',
      'add': 'Aggiungi',
      'settlement': 'Saldo',
      'settings': 'Impostazioni',
      'newTrip': 'Crea viaggio',
      'noTrips': 'Nessun viaggio. Crea il tuo primo viaggio.',
      'notStarted': 'Non iniziato',
      'pending': 'Da saldare',
      'settled': 'Saldato',
      'publicFund': 'Fondo comune',
      'members': 'Viaggiatori',
      'addExpense': 'Aggiungi spesa',
      'tripProject': 'Progetto viaggio',
      'selectTrip': 'Scegli viaggio',
      'amount': 'Importo',
      'currency': 'Valuta',
      'payer': 'Chi ha pagato?',
      'shareWith': 'Chi partecipa?',
      'equal': 'Uguale',
      'custom': 'Importo personalizzato',
      'percentage': 'Percentuale',
      'category': 'Categoria',
      'save': 'Salva',
      'cancel': 'Annulla',
      'language': 'Lingua',
      'defaultCurrency': 'Valuta predefinita',
      'whoPaysWhom': 'Trasferimenti consigliati',
      'memberStats': 'Spesa per persona',
      'paid': 'Speso',
      'shouldShare': 'Quota',
      'net': 'Saldo',
      'fundRefund': 'Rimborso fondo',
      'totalExpense': 'Spesa totale',
    },
    'th': {
      'trips': 'ทริป',
      'records': 'รายการใช้จ่าย',
      'add': 'เพิ่ม',
      'settlement': 'สรุปยอด',
      'settings': 'ตั้งค่า',
      'newTrip': 'สร้างทริปใหม่',
      'noTrips': 'ยังไม่มีทริป สร้างทริปแรกของคุณ',
      'notStarted': 'ยังไม่เริ่ม',
      'pending': 'รอสรุปยอด',
      'settled': 'สรุปแล้ว',
      'publicFund': 'กองกลาง',
      'members': 'ผู้ร่วมทริป',
      'addExpense': 'เพิ่มค่าใช้จ่าย',
      'tripProject': 'โปรเจกต์ทริป',
      'selectTrip': 'เลือกทริป',
      'amount': 'จำนวนเงิน',
      'currency': 'สกุลเงิน',
      'payer': 'ใครจ่าย?',
      'shareWith': 'ใครหาร?',
      'equal': 'เท่ากัน',
      'custom': 'กำหนดจำนวนเอง',
      'percentage': 'เปอร์เซ็นต์',
      'category': 'หมวดหมู่',
      'save': 'บันทึก',
      'cancel': 'ยกเลิก',
      'language': 'ภาษา',
      'defaultCurrency': 'สกุลเงินเริ่มต้น',
      'whoPaysWhom': 'คำแนะนำการโอนสุดท้าย',
      'memberStats': 'ค่าใช้จ่ายต่อคน',
      'paid': 'จ่าย',
      'shouldShare': 'ส่วนแบ่ง',
      'net': 'สุทธิ',
      'fundRefund': 'คืนเงินกองกลาง',
      'totalExpense': 'ค่าใช้จ่ายรวม',
    },
  };
}
