class AppStrings {
  const AppStrings(this.languageCode);

  final String languageCode;

  String t(String key) {
    final localized = _values[languageCode]?[key];
    return localized ?? _values['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'zh_Hant': {
      'appName': '旅行伴伴',
      'trips': '旅程',
      'records': '紀錄',
      'add': '新增',
      'settlement': '結算',
      'settings': '設定',
      'myTrips': '我的旅程',
      'newTrip': '建立新旅程',
      'noTrips': '還沒有旅程，先建立第一趟旅行。',
      'notStarted': '未開始',
      'pending': '待結算',
      'settled': '已結清',
      'publicFund': '公基金',
      'balance': '餘額',
      'members': '旅伴',
      'manageMembers': '管理旅伴',
      'deleteTrip': '刪除旅程',
      'expenseRecords': '支出紀錄',
      'noExpenses': '目前沒有支出紀錄',
      'addExpense': '新增支出',
      'tripProject': '旅程專案',
      'amount': '金額',
      'currency': '幣別',
      'payer': '誰付款？',
      'fund': '公基金',
      'shareWith': '誰需要分攤？',
      'selectAll': '全選',
      'clearAll': '取消全選',
      'equal': '平均',
      'custom': '自訂金額',
      'percentage': '比例',
      'remaining': '尚未分配',
      'over': '超出',
      'category': '分類',
      'title': '支出明細',
      'note': '備註',
      'save': '儲存',
      'delete': '刪除',
      'cancel': '取消',
      'language': '語言',
      'defaultCurrency': '預設幣別',
      'backup': '資料備份',
      'driveBackup': 'Google Drive 備份',
      'connectGoogle': '連結 Google Drive',
      'backupNow': '立即備份',
      'restoreDrive': '從 Google Drive 還原',
      'localBackup': '匯出 .tripbanban 備份',
      'localRestore': '匯入 .tripbanban 備份',
      'fxUpdate': '更新匯率',
      'shareSettlement': '分享結算長圖',
      'shareCsv': '匯出 CSV',
      'whoPaysWhom': '誰該給誰',
      'memberStats': '每人支出統計',
      'paid': '已支付',
      'shouldShare': '應分攤',
      'net': '淨額',
      'markPaid': '標記已付款',
      'fundNeedsRefund': '公基金仍有餘額，退款後才能完全結清。',
      'done': '完成',
      'error': '錯誤',
    },
    'zh_Hans': {
      'appName': '旅行伴伴', 'trips': '旅程', 'records': '记录', 'add': '新增', 'settlement': '结算',
      'settings': '设置', 'myTrips': '我的旅程', 'newTrip': '建立新旅程', 'noTrips': '还没有旅程，先建立第一趟旅行。',
      'notStarted': '未开始', 'pending': '待结算', 'settled': '已结清', 'publicFund': '公基金', 'balance': '余额',
      'members': '旅伴', 'manageMembers': '管理旅伴', 'deleteTrip': '删除旅程', 'expenseRecords': '支出记录',
      'noExpenses': '目前没有支出记录', 'addExpense': '新增支出', 'tripProject': '旅程项目', 'amount': '金额',
      'currency': '币别', 'payer': '谁付款？', 'fund': '公基金', 'shareWith': '谁需要分摊？', 'selectAll': '全选',
      'clearAll': '取消全选', 'equal': '平均', 'custom': '自订金额', 'percentage': '比例', 'remaining': '尚未分配',
      'over': '超出', 'category': '分类', 'title': '支出明细', 'note': '备注', 'save': '储存', 'delete': '删除',
      'cancel': '取消', 'language': '语言', 'defaultCurrency': '预设币别', 'backup': '资料备份',
      'driveBackup': 'Google Drive 备份', 'connectGoogle': '连接 Google Drive', 'backupNow': '立即备份',
      'restoreDrive': '从 Google Drive 还原', 'localBackup': '导出 .tripbanban 备份', 'localRestore': '导入 .tripbanban 备份',
      'fxUpdate': '更新汇率', 'shareSettlement': '分享结算长图', 'shareCsv': '导出 CSV', 'whoPaysWhom': '谁该给谁',
      'memberStats': '每人支出统计', 'paid': '已支付', 'shouldShare': '应分摊', 'net': '净额', 'markPaid': '标记已付款',
      'fundNeedsRefund': '公基金仍有余额，退款后才能完全结清。', 'done': '完成', 'error': '错误',
    },
    'en': {
      'appName': 'TripBanBan', 'trips': 'Trips', 'records': 'Records', 'add': 'Add', 'settlement': 'Settle',
      'settings': 'Settings', 'myTrips': 'My Trips', 'newTrip': 'New Trip', 'noTrips': 'No trips yet. Create your first trip.',
      'notStarted': 'Not started', 'pending': 'To settle', 'settled': 'Settled', 'publicFund': 'Shared fund', 'balance': 'Balance',
      'members': 'Members', 'manageMembers': 'Manage members', 'deleteTrip': 'Delete trip', 'expenseRecords': 'Expense records',
      'noExpenses': 'No expenses yet', 'addExpense': 'Add expense', 'tripProject': 'Trip', 'amount': 'Amount', 'currency': 'Currency',
      'payer': 'Who paid?', 'fund': 'Shared fund', 'shareWith': 'Who shares it?', 'selectAll': 'Select all', 'clearAll': 'Clear all',
      'equal': 'Equal', 'custom': 'Custom amount', 'percentage': 'Percentage', 'remaining': 'Remaining', 'over': 'Over',
      'category': 'Category', 'title': 'Expense detail', 'note': 'Note', 'save': 'Save', 'delete': 'Delete', 'cancel': 'Cancel',
      'language': 'Language', 'defaultCurrency': 'Default currency', 'backup': 'Backup', 'driveBackup': 'Google Drive backup',
      'connectGoogle': 'Connect Google Drive', 'backupNow': 'Back up now', 'restoreDrive': 'Restore from Google Drive',
      'localBackup': 'Export .tripbanban backup', 'localRestore': 'Import .tripbanban backup', 'fxUpdate': 'Update FX rates',
      'shareSettlement': 'Share settlement image', 'shareCsv': 'Export CSV', 'whoPaysWhom': 'Who pays whom',
      'memberStats': 'Member statistics', 'paid': 'Paid', 'shouldShare': 'Share', 'net': 'Net', 'markPaid': 'Mark paid',
      'fundNeedsRefund': 'The shared fund still has a balance. Refund it before final settlement.', 'done': 'Done', 'error': 'Error',
    },
    'ja': {
      'appName': 'TripBanBan', 'trips': '旅行', 'records': '支出記録', 'add': '追加', 'settlement': '精算', 'settings': '設定',
      'myTrips': 'マイ旅行', 'newTrip': '新しい旅行', 'noTrips': '旅行がありません。最初の旅行を作成してください。',
      'notStarted': '未開始', 'pending': '精算待ち', 'settled': '精算済み', 'publicFund': '共同資金', 'balance': '残高',
      'members': 'メンバー', 'manageMembers': 'メンバー管理', 'deleteTrip': '旅行を削除', 'expenseRecords': '支出記録',
      'noExpenses': '支出記録はありません', 'addExpense': '支出を追加', 'tripProject': '旅行', 'amount': '金額', 'currency': '通貨',
      'payer': '誰が支払いましたか？', 'fund': '共同資金', 'shareWith': '誰が負担しますか？', 'selectAll': '全選択', 'clearAll': '選択解除',
      'equal': '均等', 'custom': '金額指定', 'percentage': '割合', 'remaining': '未配分', 'over': '超過', 'category': 'カテゴリ',
      'title': '支出内容', 'note': 'メモ', 'save': '保存', 'delete': '削除', 'cancel': 'キャンセル', 'language': '言語',
      'defaultCurrency': '既定通貨', 'backup': 'バックアップ', 'driveBackup': 'Google Drive バックアップ',
      'connectGoogle': 'Google Drive に接続', 'backupNow': '今すぐバックアップ', 'restoreDrive': 'Google Drive から復元',
      'localBackup': '.tripbanban を書き出す', 'localRestore': '.tripbanban を読み込む', 'fxUpdate': '為替を更新',
      'shareSettlement': '精算画像を共有', 'shareCsv': 'CSV を出力', 'whoPaysWhom': '誰が誰に支払うか', 'memberStats': 'メンバー別統計',
      'paid': '支払済み', 'shouldShare': '負担額', 'net': '差額', 'markPaid': '支払済みにする',
      'fundNeedsRefund': '共同資金に残高があります。返金後に精算完了できます。', 'done': '完了', 'error': 'エラー',
    },
    'ko': {
      'appName': 'TripBanBan', 'trips': '여행', 'records': '지출 기록', 'add': '추가', 'settlement': '정산', 'settings': '설정',
      'myTrips': '내 여행', 'newTrip': '새 여행', 'noTrips': '여행이 없습니다. 첫 여행을 만들어 보세요.', 'notStarted': '시작 전',
      'pending': '정산 대기', 'settled': '정산 완료', 'publicFund': '공동 경비', 'balance': '잔액', 'members': '멤버',
      'manageMembers': '멤버 관리', 'deleteTrip': '여행 삭제', 'expenseRecords': '지출 기록', 'noExpenses': '지출 기록이 없습니다',
      'addExpense': '지출 추가', 'tripProject': '여행', 'amount': '금액', 'currency': '통화', 'payer': '누가 결제했나요?',
      'fund': '공동 경비', 'shareWith': '누가 분담하나요?', 'selectAll': '전체 선택', 'clearAll': '전체 해제', 'equal': '균등',
      'custom': '직접 입력', 'percentage': '비율', 'remaining': '미배분', 'over': '초과', 'category': '분류', 'title': '지출 내역',
      'note': '메모', 'save': '저장', 'delete': '삭제', 'cancel': '취소', 'language': '언어', 'defaultCurrency': '기본 통화',
      'backup': '백업', 'driveBackup': 'Google Drive 백업', 'connectGoogle': 'Google Drive 연결', 'backupNow': '지금 백업',
      'restoreDrive': 'Google Drive에서 복원', 'localBackup': '.tripbanban 백업 내보내기', 'localRestore': '.tripbanban 백업 가져오기',
      'fxUpdate': '환율 업데이트', 'shareSettlement': '정산 이미지 공유', 'shareCsv': 'CSV 내보내기', 'whoPaysWhom': '누가 누구에게 얼마를',
      'memberStats': '멤버별 통계', 'paid': '결제', 'shouldShare': '분담', 'net': '순액', 'markPaid': '결제 완료',
      'fundNeedsRefund': '공동 경비 잔액이 있습니다. 환불 후 최종 정산할 수 있습니다.', 'done': '완료', 'error': '오류',
    },
  };
}
