class CurrencyInfo {
  const CurrencyInfo({
    required this.code,
    required this.name,
    required this.symbol,
    required this.decimalPlaces,
  });

  final String code;
  final String name;
  final String symbol;
  final int decimalPlaces;
}

class CurrencyCatalog {
  const CurrencyCatalog._();

  static const List<CurrencyInfo> all = [
    CurrencyInfo(code: 'AED', name: 'UAE Dirham', symbol: 'AED', decimalPlaces: 2),
    CurrencyInfo(code: 'AFN', name: 'Afghani', symbol: 'AFN', decimalPlaces: 0),
    CurrencyInfo(code: 'ALL', name: 'Lek', symbol: 'ALL', decimalPlaces: 0),
    CurrencyInfo(code: 'AMD', name: 'Armenian Dram', symbol: 'AMD', decimalPlaces: 2),
    CurrencyInfo(code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ANG', decimalPlaces: 2),
    CurrencyInfo(code: 'AOA', name: 'Kwanza', symbol: 'AOA', decimalPlaces: 2),
    CurrencyInfo(code: 'ARS', name: 'Argentine Peso', symbol: 'ARS', decimalPlaces: 2),
    CurrencyInfo(code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimalPlaces: 2),
    CurrencyInfo(code: 'AWG', name: 'Aruban Florin', symbol: 'AWG', decimalPlaces: 2),
    CurrencyInfo(code: 'AZN', name: 'Azerbaijan Manat', symbol: 'AZN', decimalPlaces: 2),
    CurrencyInfo(code: 'BAM', name: 'Convertible Mark', symbol: 'BAM', decimalPlaces: 2),
    CurrencyInfo(code: 'BBD', name: 'Barbados Dollar', symbol: 'BBD', decimalPlaces: 2),
    CurrencyInfo(code: 'BDT', name: 'Taka', symbol: 'BDT', decimalPlaces: 2),
    CurrencyInfo(code: 'BGN', name: 'Bulgarian Lev', symbol: 'BGN', decimalPlaces: 2),
    CurrencyInfo(code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD', decimalPlaces: 3),
    CurrencyInfo(code: 'BIF', name: 'Burundi Franc', symbol: 'BIF', decimalPlaces: 0),
    CurrencyInfo(code: 'BMD', name: 'Bermudian Dollar', symbol: 'BMD', decimalPlaces: 2),
    CurrencyInfo(code: 'BND', name: 'Brunei Dollar', symbol: 'BND', decimalPlaces: 2),
    CurrencyInfo(code: 'BOB', name: 'Boliviano', symbol: 'BOB', decimalPlaces: 2),
    CurrencyInfo(code: 'BOV', name: 'Mvdol', symbol: 'BOV', decimalPlaces: 2),
    CurrencyInfo(code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2),
    CurrencyInfo(code: 'BSD', name: 'Bahamian Dollar', symbol: 'BSD', decimalPlaces: 2),
    CurrencyInfo(code: 'BTN', name: 'Ngultrum', symbol: 'BTN', decimalPlaces: 2),
    CurrencyInfo(code: 'BWP', name: 'Pula', symbol: 'BWP', decimalPlaces: 2),
    CurrencyInfo(code: 'BYN', name: 'Belarusian Ruble', symbol: 'BYN', decimalPlaces: 2),
    CurrencyInfo(code: 'BZD', name: 'Belize Dollar', symbol: 'BZD', decimalPlaces: 2),
    CurrencyInfo(code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', decimalPlaces: 2),
    CurrencyInfo(code: 'CDF', name: 'Congolese Franc', symbol: 'CDF', decimalPlaces: 2),
    CurrencyInfo(code: 'CHE', name: 'WIR Euro', symbol: 'CHE', decimalPlaces: 2),
    CurrencyInfo(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimalPlaces: 2),
    CurrencyInfo(code: 'CHW', name: 'WIR Franc', symbol: 'CHW', decimalPlaces: 2),
    CurrencyInfo(code: 'CLF', name: 'Unidad de Fomento', symbol: 'CLF', decimalPlaces: 4),
    CurrencyInfo(code: 'CLP', name: 'Chilean Peso', symbol: 'CLP', decimalPlaces: 0),
    CurrencyInfo(code: 'CNY', name: 'Yuan Renminbi', symbol: 'CN¥', decimalPlaces: 2),
    CurrencyInfo(code: 'COP', name: 'Colombian Peso', symbol: 'COP', decimalPlaces: 2),
    CurrencyInfo(code: 'COU', name: 'Unidad de Valor Real', symbol: 'COU', decimalPlaces: 2),
    CurrencyInfo(code: 'CRC', name: 'Costa Rican Colon', symbol: 'CRC', decimalPlaces: 2),
    CurrencyInfo(code: 'CUC', name: 'Peso Convertible', symbol: 'CUC', decimalPlaces: 2),
    CurrencyInfo(code: 'CUP', name: 'Cuban Peso', symbol: 'CUP', decimalPlaces: 2),
    CurrencyInfo(code: 'CVE', name: 'Cabo Verde Escudo', symbol: 'CVE', decimalPlaces: 2),
    CurrencyInfo(code: 'CZK', name: 'Czech Koruna', symbol: 'CZK', decimalPlaces: 2),
    CurrencyInfo(code: 'DJF', name: 'Djibouti Franc', symbol: 'DJF', decimalPlaces: 0),
    CurrencyInfo(code: 'DKK', name: 'Danish Krone', symbol: 'DKK', decimalPlaces: 2),
    CurrencyInfo(code: 'DOP', name: 'Dominican Peso', symbol: 'DOP', decimalPlaces: 2),
    CurrencyInfo(code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD', decimalPlaces: 2),
    CurrencyInfo(code: 'EGP', name: 'Egyptian Pound', symbol: 'EGP', decimalPlaces: 2),
    CurrencyInfo(code: 'ERN', name: 'Nakfa', symbol: 'ERN', decimalPlaces: 2),
    CurrencyInfo(code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB', decimalPlaces: 2),
    CurrencyInfo(code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2),
    CurrencyInfo(code: 'FJD', name: 'Fiji Dollar', symbol: 'FJD', decimalPlaces: 2),
    CurrencyInfo(code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FKP', decimalPlaces: 2),
    CurrencyInfo(code: 'GBP', name: 'Pound Sterling', symbol: '£', decimalPlaces: 2),
    CurrencyInfo(code: 'GEL', name: 'Lari', symbol: 'GEL', decimalPlaces: 2),
    CurrencyInfo(code: 'GHS', name: 'Ghana Cedi', symbol: 'GHS', decimalPlaces: 2),
    CurrencyInfo(code: 'GIP', name: 'Gibraltar Pound', symbol: 'GIP', decimalPlaces: 2),
    CurrencyInfo(code: 'GMD', name: 'Dalasi', symbol: 'GMD', decimalPlaces: 2),
    CurrencyInfo(code: 'GNF', name: 'Guinean Franc', symbol: 'GNF', decimalPlaces: 0),
    CurrencyInfo(code: 'GTQ', name: 'Quetzal', symbol: 'GTQ', decimalPlaces: 2),
    CurrencyInfo(code: 'GYD', name: 'Guyana Dollar', symbol: 'GYD', decimalPlaces: 2),
    CurrencyInfo(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', decimalPlaces: 2),
    CurrencyInfo(code: 'HNL', name: 'Lempira', symbol: 'HNL', decimalPlaces: 2),
    CurrencyInfo(code: 'HRK', name: 'Kuna', symbol: 'HRK', decimalPlaces: 2),
    CurrencyInfo(code: 'HTG', name: 'Gourde', symbol: 'HTG', decimalPlaces: 2),
    CurrencyInfo(code: 'HUF', name: 'Forint', symbol: 'HUF', decimalPlaces: 2),
    CurrencyInfo(code: 'IDR', name: 'Rupiah', symbol: 'IDR', decimalPlaces: 2),
    CurrencyInfo(code: 'ILS', name: 'New Israeli Sheqel', symbol: '₪', decimalPlaces: 2),
    CurrencyInfo(code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2),
    CurrencyInfo(code: 'IQD', name: 'Iraqi Dinar', symbol: 'IQD', decimalPlaces: 0),
    CurrencyInfo(code: 'IRR', name: 'Iranian Rial', symbol: 'IRR', decimalPlaces: 0),
    CurrencyInfo(code: 'ISK', name: 'Iceland Krona', symbol: 'ISK', decimalPlaces: 0),
    CurrencyInfo(code: 'JMD', name: 'Jamaican Dollar', symbol: 'JMD', decimalPlaces: 2),
    CurrencyInfo(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD', decimalPlaces: 3),
    CurrencyInfo(code: 'JPY', name: 'Yen', symbol: '¥', decimalPlaces: 0),
    CurrencyInfo(code: 'KES', name: 'Kenyan Shilling', symbol: 'KES', decimalPlaces: 2),
    CurrencyInfo(code: 'KGS', name: 'Som', symbol: 'KGS', decimalPlaces: 2),
    CurrencyInfo(code: 'KHR', name: 'Riel', symbol: 'KHR', decimalPlaces: 2),
    CurrencyInfo(code: 'KMF', name: 'Comorian Franc', symbol: 'KMF', decimalPlaces: 0),
    CurrencyInfo(code: 'KPW', name: 'North Korean Won', symbol: 'KPW', decimalPlaces: 0),
    CurrencyInfo(code: 'KRW', name: 'Won', symbol: '₩', decimalPlaces: 0),
    CurrencyInfo(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD', decimalPlaces: 3),
    CurrencyInfo(code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'KYD', decimalPlaces: 2),
    CurrencyInfo(code: 'KZT', name: 'Tenge', symbol: 'KZT', decimalPlaces: 2),
    CurrencyInfo(code: 'LAK', name: 'Lao Kip', symbol: 'LAK', decimalPlaces: 0),
    CurrencyInfo(code: 'LBP', name: 'Lebanese Pound', symbol: 'LBP', decimalPlaces: 0),
    CurrencyInfo(code: 'LKR', name: 'Sri Lanka Rupee', symbol: 'LKR', decimalPlaces: 2),
    CurrencyInfo(code: 'LRD', name: 'Liberian Dollar', symbol: 'LRD', decimalPlaces: 2),
    CurrencyInfo(code: 'LSL', name: 'Loti', symbol: 'LSL', decimalPlaces: 2),
    CurrencyInfo(code: 'LYD', name: 'Libyan Dinar', symbol: 'LYD', decimalPlaces: 3),
    CurrencyInfo(code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', decimalPlaces: 2),
    CurrencyInfo(code: 'MDL', name: 'Moldovan Leu', symbol: 'MDL', decimalPlaces: 2),
    CurrencyInfo(code: 'MGA', name: 'Malagasy Ariary', symbol: 'MGA', decimalPlaces: 0),
    CurrencyInfo(code: 'MKD', name: 'Denar', symbol: 'MKD', decimalPlaces: 2),
    CurrencyInfo(code: 'MMK', name: 'Kyat', symbol: 'MMK', decimalPlaces: 0),
    CurrencyInfo(code: 'MNT', name: 'Tugrik', symbol: 'MNT', decimalPlaces: 2),
    CurrencyInfo(code: 'MOP', name: 'Pataca', symbol: 'MOP', decimalPlaces: 2),
    CurrencyInfo(code: 'MRU', name: 'Ouguiya', symbol: 'MRU', decimalPlaces: 2),
    CurrencyInfo(code: 'MUR', name: 'Mauritius Rupee', symbol: 'MUR', decimalPlaces: 2),
    CurrencyInfo(code: 'MVR', name: 'Rufiyaa', symbol: 'MVR', decimalPlaces: 2),
    CurrencyInfo(code: 'MWK', name: 'Malawi Kwacha', symbol: 'MWK', decimalPlaces: 2),
    CurrencyInfo(code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', decimalPlaces: 2),
    CurrencyInfo(code: 'MXV', name: 'Mexican Unidad de Inversion (UDI)', symbol: 'MXV', decimalPlaces: 2),
    CurrencyInfo(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'MYR', decimalPlaces: 2),
    CurrencyInfo(code: 'MZN', name: 'Mozambique Metical', symbol: 'MZN', decimalPlaces: 2),
    CurrencyInfo(code: 'NAD', name: 'Namibia Dollar', symbol: 'NAD', decimalPlaces: 2),
    CurrencyInfo(code: 'NGN', name: 'Naira', symbol: 'NGN', decimalPlaces: 2),
    CurrencyInfo(code: 'NIO', name: 'Cordoba Oro', symbol: 'NIO', decimalPlaces: 2),
    CurrencyInfo(code: 'NOK', name: 'Norwegian Krone', symbol: 'NOK', decimalPlaces: 2),
    CurrencyInfo(code: 'NPR', name: 'Nepalese Rupee', symbol: 'NPR', decimalPlaces: 2),
    CurrencyInfo(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimalPlaces: 2),
    CurrencyInfo(code: 'OMR', name: 'Rial Omani', symbol: 'OMR', decimalPlaces: 3),
    CurrencyInfo(code: 'PAB', name: 'Balboa', symbol: 'PAB', decimalPlaces: 2),
    CurrencyInfo(code: 'PEN', name: 'Sol', symbol: 'PEN', decimalPlaces: 2),
    CurrencyInfo(code: 'PGK', name: 'Kina', symbol: 'PGK', decimalPlaces: 2),
    CurrencyInfo(code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimalPlaces: 2),
    CurrencyInfo(code: 'PKR', name: 'Pakistan Rupee', symbol: 'PKR', decimalPlaces: 2),
    CurrencyInfo(code: 'PLN', name: 'Zloty', symbol: 'PLN', decimalPlaces: 2),
    CurrencyInfo(code: 'PYG', name: 'Guarani', symbol: 'PYG', decimalPlaces: 0),
    CurrencyInfo(code: 'QAR', name: 'Qatari Rial', symbol: 'QAR', decimalPlaces: 2),
    CurrencyInfo(code: 'RON', name: 'Romanian Leu', symbol: 'RON', decimalPlaces: 2),
    CurrencyInfo(code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD', decimalPlaces: 0),
    CurrencyInfo(code: 'RUB', name: 'Russian Ruble', symbol: 'RUB', decimalPlaces: 2),
    CurrencyInfo(code: 'RWF', name: 'Rwanda Franc', symbol: 'RWF', decimalPlaces: 0),
    CurrencyInfo(code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', decimalPlaces: 2),
    CurrencyInfo(code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SBD', decimalPlaces: 2),
    CurrencyInfo(code: 'SCR', name: 'Seychelles Rupee', symbol: 'SCR', decimalPlaces: 2),
    CurrencyInfo(code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', decimalPlaces: 2),
    CurrencyInfo(code: 'SEK', name: 'Swedish Krona', symbol: 'SEK', decimalPlaces: 2),
    CurrencyInfo(code: 'SGD', name: 'Singapore Dollar', symbol: 'SGD', decimalPlaces: 2),
    CurrencyInfo(code: 'SHP', name: 'Saint Helena Pound', symbol: 'SHP', decimalPlaces: 2),
    CurrencyInfo(code: 'SLE', name: 'Leone', symbol: 'SLE', decimalPlaces: 2),
    CurrencyInfo(code: 'SLL', name: 'Leone', symbol: 'SLL', decimalPlaces: 0),
    CurrencyInfo(code: 'SOS', name: 'Somali Shilling', symbol: 'SOS', decimalPlaces: 0),
    CurrencyInfo(code: 'SRD', name: 'Surinam Dollar', symbol: 'SRD', decimalPlaces: 2),
    CurrencyInfo(code: 'SSP', name: 'South Sudanese Pound', symbol: 'SSP', decimalPlaces: 2),
    CurrencyInfo(code: 'STN', name: 'Dobra', symbol: 'STN', decimalPlaces: 2),
    CurrencyInfo(code: 'SVC', name: 'El Salvador Colon', symbol: 'SVC', decimalPlaces: 2),
    CurrencyInfo(code: 'SYP', name: 'Syrian Pound', symbol: 'SYP', decimalPlaces: 0),
    CurrencyInfo(code: 'SZL', name: 'Lilangeni', symbol: 'SZL', decimalPlaces: 2),
    CurrencyInfo(code: 'THB', name: 'Baht', symbol: 'THB', decimalPlaces: 2),
    CurrencyInfo(code: 'TJS', name: 'Somoni', symbol: 'TJS', decimalPlaces: 2),
    CurrencyInfo(code: 'TMT', name: 'Turkmenistan New Manat', symbol: 'TMT', decimalPlaces: 2),
    CurrencyInfo(code: 'TND', name: 'Tunisian Dinar', symbol: 'TND', decimalPlaces: 3),
    CurrencyInfo(code: 'TOP', name: 'Pa’anga', symbol: 'TOP', decimalPlaces: 2),
    CurrencyInfo(code: 'TRY', name: 'Turkish Lira', symbol: 'TRY', decimalPlaces: 2),
    CurrencyInfo(code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TTD', decimalPlaces: 2),
    CurrencyInfo(code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', decimalPlaces: 2),
    CurrencyInfo(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS', decimalPlaces: 2),
    CurrencyInfo(code: 'UAH', name: 'Hryvnia', symbol: 'UAH', decimalPlaces: 2),
    CurrencyInfo(code: 'UGX', name: 'Uganda Shilling', symbol: 'UGX', decimalPlaces: 0),
    CurrencyInfo(code: 'USD', name: 'US Dollar', symbol: '$', decimalPlaces: 2),
    CurrencyInfo(code: 'USN', name: 'US Dollar (Next day)', symbol: 'USN', decimalPlaces: 2),
    CurrencyInfo(code: 'UYI', name: 'Uruguay Peso en Unidades Indexadas (UI)', symbol: 'UYI', decimalPlaces: 0),
    CurrencyInfo(code: 'UYU', name: 'Peso Uruguayo', symbol: 'UYU', decimalPlaces: 2),
    CurrencyInfo(code: 'UYW', name: 'Unidad Previsional', symbol: 'UYW', decimalPlaces: 4),
    CurrencyInfo(code: 'UZS', name: 'Uzbekistan Sum', symbol: 'UZS', decimalPlaces: 2),
    CurrencyInfo(code: 'VED', name: 'Bolívar Soberano', symbol: 'VED', decimalPlaces: 2),
    CurrencyInfo(code: 'VES', name: 'Bolívar Soberano', symbol: 'VES', decimalPlaces: 2),
    CurrencyInfo(code: 'VND', name: 'Dong', symbol: '₫', decimalPlaces: 0),
    CurrencyInfo(code: 'VUV', name: 'Vatu', symbol: 'VUV', decimalPlaces: 0),
    CurrencyInfo(code: 'WST', name: 'Tala', symbol: 'WST', decimalPlaces: 2),
    CurrencyInfo(code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA', decimalPlaces: 0),
    CurrencyInfo(code: 'XAG', name: 'Silver', symbol: 'XAG', decimalPlaces: 2),
    CurrencyInfo(code: 'XAU', name: 'Gold', symbol: 'XAU', decimalPlaces: 2),
    CurrencyInfo(code: 'XBA', name: 'Bond Markets Unit European Composite Unit (EURCO)', symbol: 'XBA', decimalPlaces: 2),
    CurrencyInfo(code: 'XBB', name: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', symbol: 'XBB', decimalPlaces: 2),
    CurrencyInfo(code: 'XBC', name: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', symbol: 'XBC', decimalPlaces: 2),
    CurrencyInfo(code: 'XBD', name: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', symbol: 'XBD', decimalPlaces: 2),
    CurrencyInfo(code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', decimalPlaces: 2),
    CurrencyInfo(code: 'XDR', name: 'SDR (Special Drawing Right)', symbol: 'XDR', decimalPlaces: 2),
    CurrencyInfo(code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'F CFA', decimalPlaces: 0),
    CurrencyInfo(code: 'XPD', name: 'Palladium', symbol: 'XPD', decimalPlaces: 2),
    CurrencyInfo(code: 'XPF', name: 'CFP Franc', symbol: 'CFPF', decimalPlaces: 0),
    CurrencyInfo(code: 'XPT', name: 'Platinum', symbol: 'XPT', decimalPlaces: 2),
    CurrencyInfo(code: 'XSU', name: 'Sucre', symbol: 'XSU', decimalPlaces: 2),
    CurrencyInfo(code: 'XTS', name: 'Codes specifically reserved for testing purposes', symbol: 'XTS', decimalPlaces: 2),
    CurrencyInfo(code: 'XUA', name: 'ADB Unit of Account', symbol: 'XUA', decimalPlaces: 2),
    CurrencyInfo(code: 'XXX', name: 'The codes assigned for transactions where no currency is involved', symbol: '¤', decimalPlaces: 2),
    CurrencyInfo(code: 'YER', name: 'Yemeni Rial', symbol: 'YER', decimalPlaces: 0),
    CurrencyInfo(code: 'ZAR', name: 'Rand', symbol: 'ZAR', decimalPlaces: 2),
    CurrencyInfo(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZMW', decimalPlaces: 2),
    CurrencyInfo(code: 'ZWL', name: 'Zimbabwe Dollar', symbol: 'ZWL', decimalPlaces: 2),
  ];

  static final Map<String, CurrencyInfo> _byCode = {
    for (final item in all) item.code: item,
  };

  static CurrencyInfo? find(String code) => _byCode[code.toUpperCase()];

  static int decimalPlacesFor(String code) => find(code)?.decimalPlaces ?? 2;
}
